import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "remixicon/fonts/remixicon.css";
import ScrollTop from "@/components/ScrollTop";

const fontPoppins = Poppins ({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Warung Technology",
  description: "Generated by Wartech",
  icons:{
    icon: '/favicon.png'
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className= {`${fontPoppins.className} antialiased`}>
        <ScrollTop />
        <Navbar/>
        <div className="container mx-auto px-4">{children}</div>
        <Footer />
        </body>
    </html>
  );
}